# Generated by Django 5.0.6 on 2026-04-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailrecord_address_line1_emailrecord_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
