# Generated by Django 6.0.4 on 2026-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailrecord_custom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Email address where this email came from', max_length=254, null=True),
        ),
    ]
